# Generated by Django 2.2 on 2019-12-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=100)),
                ('award', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
